export const exclusiveByCategorySpeakers = [
  {
    Category: "BUSINESS",
    Speakers: [
      { Name: "Jennifer Aaker" },
      { Name: "Komal Ahmad" },
      { Name: "Naomi Bagdonas" },
      { Name: "George Blankenship" },
      { Name: "Laszlo Bock" },
      { Name: "Sarah Brown" },
      { Name: "Kevin Carroll" },
      { Name: "Steve Case" },
      { Name: "Aneesh Chopra" },
      { Name: "Stephanie Chung" },
      { Name: "Kat Cole" },
      { Name: "Amy Cuddy" },
      { Name: "Lee Eisenberg" },
      { Name: "Nicholas Epley" },
      { Name: "Paula Faris" },
      { Name: "Obi Felten" },
      { Name: "Dr. Lisa Genova" },
      { Name: "Louis Gerstner Jr." },
      { Name: "Jennifer Golbeck" },
      { Name: "Adam Grant" },
      { Name: "Gary Heil" },
      { Name: "Marillyn Hewson" },
      { Name: "Arianna Huffington" },
      { Name: "Jeff Immelt" },
      { Name: "Walter Isaacson" },
      { Name: "Hubert Joly" },
      { Name: "Mark King" },
      { Name: "Martin Lindstrom" },
      { Name: "Jim McNerney" },
      { Name: "Rebecca Messina" },
      { Name: "Jonathan Mildenhall" },
      { Name: "Ethan Mollick" },
      { Name: "Richard Montañez" },
      { Name: "Monty Moran" },
      { Name: "Alan Mulally" },
      { Name: "Liz Murray" },
      { Name: "Daniel Pink" },
      { Name: "Ann Rhoades" },
      { Name: "Horst Schulze" },
      { Name: "Tony Scott" },
      { Name: "Marissa Shandell" },
      { Name: "Daniel Shapiro" },
      { Name: "Megan Smith" },
      { Name: "Jim Stengel" },
      { Name: "William Taylor" },
      { Name: "Michele Thornton Ghee" },
      { Name: "Peter Ueberroth" },
      { Name: "Ozan Varol" },
      { Name: "Luke Williams" },
      { Name: "Lee Woodruff" },
    ],
  },
  {
    Category: "ECONOMICS & FINANCE",
    Speakers: [
      { Name: "Ben S. Bernanke" },
      { Name: "Mark Carney" },
      { Name: "Brian Deese" },
      { Name: "William Dudley" },
      { Name: "Charles Evans" },
      { Name: "Roger Ferguson" },
      { Name: "Richard Fisher" },
      { Name: "Jason Furman" },
      { Name: "Lord Mervyn King" },
      { Name: "Donald Kohn" },
      { Name: "David Malpass" },
      { Name: "Rebecca Patterson" },
      { Name: "Christina Romer" },
      { Name: "Mary L. Schapiro" },
      { Name: "John Snow" },
      { Name: "Jeremy C. Stein" },
      { Name: "Neal S. Wolin" },
    ],
  },
  {
    Category: "ENERGY, CLIMATE, SUSTAINABILITY",
    Speakers: [
      { Name: "Steven Chu" },
      { Name: "Andy Karsner" },
      { Name: "Ernest Moniz" },
    ],
  },
  {
    Category: "ENTERTAINMENT",
    Speakers: [
      { Name: "Jose Andres" },
      { Name: "Bear Grylls" },
      { Name: "Jenna Hager" },
      { Name: "Jerry Linenger" },
      { Name: "Alexi Pappas" },
      { Name: "Platon" },
    ],
  },
  {
    Category: "HEALTH",
    Speakers: [
      { Name: "Barbara Pierce Bush" },
      { Name: "Doro Bush Koch" },
      { Name: "Sam Kass" },
      { Name: "Mark McClellan, M.D." },
      { Name: "John Whyte" },
    ],
  },
  {
    Category: "HISTORY",
    Speakers: [
      { Name: "Douglas Brinkley" },
      { Name: "Doris Kearns Goodwin" },
      { Name: "Nancy Koehn" },
    ],
  },
  {
    Category: "MEDIA",
    Speakers: [
      { Name: "Christiane Amanpour" },
      { Name: "Bret Baier" },
      { Name: "Ann Compton" },
      { Name: "Katie Couric" },
      { Name: "David Gregory" },
      { Name: "John Heilemann" },
      { Name: "Hugh Hewitt" },
      { Name: "Ezra Klein" },
      { Name: "Ted Koppel" },
      { Name: "Eugene Robinson" },
      { Name: "Frank Sesno" },
      { Name: "Claire Shipman" },
      { Name: "George Stephanopoulos" },
      { Name: "Meredith Vieira" },
      { Name: "Bob Woodruff" },
      { Name: "Judy Woodruff" },
    ],
  },
  {
    Category: "Military & Geopolitics",
    Speakers: [
      { Name: "Gen. Keith Alexander, USA (Ret.)" },
      { Name: "John Brennan" },
      { Name: "Kyle Carpenter" },
      { Name: "Dan Coats" },
      { Name: "Gen. Martin E. Dempsey, U.S. Army (Retired)" },
      { Name: "Robert Gates" },
      { Name: "Sal Giunta" },
      { Name: "Richard Haass" },
      { Name: "Chuck Hagel" },
      { Name: "Gen. James N. Mattis, USMC (Ret.)" },
      { Name: "Michael McFaul" },
      { Name: "Adm. William H. McRaven, USN (Ret.)" },
      { Name: "Leon Panetta" },
      { Name: "Gen. David H. Petraeus, U.S. Army (Retired)" },
      { Name: "Condoleezza Rice" },
      { Name: "Lt. Col. Dan Rooney, USAF" },
      { Name: "Adm. James Stavridis, USN (Ret.)" },
      { Name: "George Tenet" },
      { Name: "Frances Townsend" },
    ],
  },
  {
    Category: "POLITICS",
    Speakers: [
      { Name: "David Axelrod" },
      { Name: "Jose Maria Aznar" },
      { Name: "James Baker III" },
      { Name: "Jose Manuel Barroso" },
      { Name: "Paul Begala" },
      { Name: "John Bolton" },
      { Name: "Erskine Bowles" },
      { Name: "Bill Bradley" },
      { Name: "Jeb Bush" },
      { Name: "Laura W. Bush" },
      { Name: "Andrew Card" },
      { Name: "Jay Carney" },
      { Name: "Michelle Caruso-Cabrera" },
      { Name: "James Carville" },
      { Name: "Alex Castellanos" },
      { Name: "Liz Cheney" },
      { Name: "William Cohen" },
      { Name: "James Comey" },
      { Name: "Mitch Daniels" },
      { Name: "Christopher Dodd" },
      { Name: "Jon Favreau" },
      { Name: "David Gergen" },
      { Name: "Stephen Hayes" },
      { Name: "Asa Hutchinson" },
      { Name: "Bobby Jindal" },
      { Name: "William Kristol" },
      { Name: "Mary Matalin" },
      { Name: "Sylvia Mathews Burwell" },
      { Name: "Claire McCaskill" },
      { Name: "Janet Napolitano" },
      { Name: "Bill Press" },
      { Name: "Reince Priebus" },
      { Name: "Tom Ridge" },
      { Name: "Susan Schwab" },
      { Name: "Alan Simpson" },
      { Name: "J.C. Watts" },
      { Name: "Christine Todd Whitman" },
      { Name: "George F. Will" },
    ],
  },
  {
    Category: "SPORTS",
    Speakers: [
      { Name: "Shane Battier" },
      { Name: "Terry Bradshaw" },
      { Name: "Jim Calhoun" },
      { Name: "Tony Dungy" },
      { Name: "Jill Ellis" },
      { Name: "Joe Gibbs" },
      { Name: "Lou Holtz" },
      { Name: "Mike Krzyzewski" },
      { Name: "Tony La Russa" },
      { Name: "Ted Leonsis" },
      { Name: "Jack Nicklaus" },
      { Name: "Gary Player" },
      { Name: "Mary Lou Retton" },
      { Name: "Mariano Rivera" },
      { Name: "Ron Rivera" },
      { Name: "Anthony Robles" },
      { Name: "Bonnie St. John" },
      { Name: "Dick Vitale" },
      { Name: "Mallory Weggemann" },
    ],
  },
  {
    Category: "WORLD LEADERS",
    Speakers: [
      { Name: "Tony Blair" },
      { Name: "Gordon Brown" },
      { Name: "George W. Bush" },
      { Name: "The Rt. Hon. Sir John Major, KG, CH" },
      { Name: "Theresa May" },
      { Name: "Brian Mulroney" },
      { Name: "Anders Fogh Rasmussen" },
    ],
  },
];
